apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resources-reader
  namespace: default
subjects:
- kind: User
  name: kube-user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-pod-reader
  apiGroup: rbac.authorization.k8s.io
