apiVersion: v1
kind: Pod
metadata:
  name: env-test-pod
  labels:
    app: env-test-pod
spec:
  containers:
  - name: env-test-container
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","sleep 600"]
    resources:
      limits:
        memory: 64Mi
        cpu: 250m
    volumeMounts:
    - name: podinfo
      mountPath: /podinfo
      readOnly: false    
  volumes:
  - name: podinfo
    downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          fieldPath: metadata.name
        path: pod_name
      - fieldRef:
          fieldPath: metadata.namespace
        path: pod_namespace
      - fieldRef:
          fieldPath: metadata.labels
        path: pod_labels
      - resourceFieldRef:
          containerName: env-test-container
          resource: limits.cpu
        path: pod_cpu
      - resourceFieldRef:
          containerName: env-test-container
          resource: limits.memory
          divisor: 1Mi
        path: pod_mem
  restartPolicy: Never
          
