apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  - image: ikubernetes/myapp:v6
    name: app1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: emptydir
      mountPath: /emptydir
  - image: busybox:latest
    name: app2
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","sleep 3600"]
    volumeMounts:
    - name: emptydir
      mountPath: /emptydir
  volumes:
  - name: emptydir
    emptyDir: {}
