apiVersion: v1
kind: Pod
metadata:
  name: myapp-hostpath
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v6
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: webdata
      mountPath: usr/share/nginx/html/
  volumes:
  - name: webdata
    hostPath:
      path: /data/webdata/
