apiVersion: v1
kind: Pod
metadata:
  name: myapp-nfs
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v6
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: webdata
      mountPath: usr/share/nginx/html/
  volumes:
  - name: webdata
    nfs:
      path: /data/webdata/
      server: 192.168.47.141
