apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-demo
spec:
  containers:
  - name: myapp-pvc
    image: ikubernetes/myapp:v6
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: myapp-http
    volumeMounts:
    - name: pvc-vol
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: pvc-vol
    persistentVolumeClaim:
      claimName: pvc-demo 
