apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-vol-demo2
spec:
  containers:
  - name: pod-cm-vol2
    image: ikubernetes/myapp:v7
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: user
      mountPath: /user/
  volumes:
  - name: user
    configMap:
      name: cm-demo
      items:
      - key: user
        path: ./user
