apiVersion: v1
kind: Pod
metadata:
  name: redis-vol-nfs
  labels:
    app: redis
spec:
  volumes:
  - name: redis-data
    nfs:
      path: /data/redis
      server: 192.168.47.141
  containers:
  - name: redis
    image: redis:4.0-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - name: redis-port
      containerPort: 6379
    volumeMounts:
    - name: redis-data
      mountPath: /data
