apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-init
  labels:
    app: myapp-init
spec:
  containers:
  - name: myapp-container
    image: ikubernetes/myapp:v7
    imagePullPolicy: IfNotPresent
  initContainers:
  - name: init-something
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh","-c","sleep 15"]
