apiVersion: v1
kind: Pod
metadata:
  name: myapp-sa
spec:
  serviceAccountName: sa-demo
  containers:
  - name: myapp-sa
    image: ikubernetes/myapp:v6
    imagePullPolicy: IfNotPresent
    ports:
    - name: httpport
      containerPort: 80
