apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
spec: 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  namespace: test-ns
spec:
  replicas: 2
  selector:
    app: myapp-rc
  template:
    metadata:
      labels:
        app: myapp-rc
    spec:
      containers:
      - name: myapp-rc
        image: ikubernetes/myapp:v7

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-rc
  namespace: test-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp-rc
