apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-ns
spec:
  containers:
  - name: test-pod
    image: nginx:latest
    ports:
    - containerPort: 8888
      protocol: TCP
      
