---

- hosts: lab
  remote_user: root
  
  tasks:
  - name: install httpd service
    yum: name=httpd state=present

  - name: copy httpd conf file
    copy: src=/root/ansible/httpd.conf dest=/etc/httpd/conf
    notify: restart httpd

  - name: start httpd service
    service: name=httpd state=started enabled=yes  

  handlers:
  - name: restart httpd
    service: name=httpd state=restarted 
