apiVersion: v1
kind: Pod
metadata:
  name: myapp-secret
  namespace: default
spec:
  containers:
    - name: myapp-secret
      image: ikubernetes/myapp:v7
      ports:
        - containerPort: 80
      env:
      - name: MySQL-PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: mysql-root-password
