---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-vol-pvc
  namespace: default
  labels:
    app: myapp-vol-pvc
spec:
  containers:
  - name: myapp-vol-pvc
    image: ikubernetes/myapp:v7
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-vol-pvc
  namespace: default
spec:
  ports:
  - name: 80-80
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: myapp-vol-pvc
