---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-vol-empty
  namespace: default
spec:
  containers:
  - name: myapp1
    image: ikubernetes/myapp:v7
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  - name: myapp2
    image: ikubernetes/myapp:v7
    command: ["/bin/sh","-c","while true;do echo $(date) > /tmp/index.html;sleep 1;done"]
    volumeMounts:
    - name: nginx-data
      mountPath: /tmp
  volumes:
  - name: nginx-data
    emptyDir: {}
