---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-nginx
  namespace: default
data:
  NGX_PORT: "8080"
  NGX_HOSTNAME: weijuwei
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-configmap
  namespace: default
spec:
  containers:
  - name: myapp-configmap
    image: ikubernetes/myapp:v7
    ports:
      - containerPort: 80
    env:
    #- name: myapp-vol-pvc-hostname
    #  value: env
    - name: nginx_port
      valueFrom:
        configMapKeyRef:
          key: NGX_PORT
          name: cm-nginx
    - name: nginx_hostname
      valueFrom:
        configMapKeyRef:
          key: NGX_HOSTNAME
          name: cm-nginx
